// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kH20WE8pCAm-cMgdFBgJM78e39thEcM',
    appId: '1:653167376608:web:5cce2c4c78c17cc0987885',
    messagingSenderId: '653167376608',
    projectId: 'medbridge-11d7e',
    authDomain: 'medbridge-11d7e.firebaseapp.com',
    storageBucket: 'medbridge-11d7e.firebasestorage.app',
    measurementId: 'G-81DBSP131J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQl86yhCjyarTS-rtQf3vkXNchra7L3ag',
    appId: '1:653167376608:android:ffd6c9318c9c164b987885',
    messagingSenderId: '653167376608',
    projectId: 'medbridge-11d7e',
    storageBucket: 'medbridge-11d7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mZy2ijgbm2UlR-0GXL6kJ3tkwc6ckaQ',
    appId: '1:653167376608:ios:357ab8de1b9be102987885',
    messagingSenderId: '653167376608',
    projectId: 'medbridge-11d7e',
    storageBucket: 'medbridge-11d7e.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mZy2ijgbm2UlR-0GXL6kJ3tkwc6ckaQ',
    appId: '1:653167376608:ios:357ab8de1b9be102987885',
    messagingSenderId: '653167376608',
    projectId: 'medbridge-11d7e',
    storageBucket: 'medbridge-11d7e.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kH20WE8pCAm-cMgdFBgJM78e39thEcM',
    appId: '1:653167376608:web:381a5518dea8b3d9987885',
    messagingSenderId: '653167376608',
    projectId: 'medbridge-11d7e',
    authDomain: 'medbridge-11d7e.firebaseapp.com',
    storageBucket: 'medbridge-11d7e.firebasestorage.app',
    measurementId: 'G-44S4WH8MQL',
  );
}
